name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit and pytest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: pip

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Run pytest
        run: |
          python -m pytest --timeout=10 tests

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    if: github.repository == 'Xtherma/xtherma_ha'
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v5"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: "topics"

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v5"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
